/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my_first_gradle_project;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
}
